const data = {
  products: [
    {
      name: 'L7 9.05',
      slug: 'l7-905',
      category: 'Asics',
      image: '/images/L7.png',
      manufaturer: 'Bitmain',
      price: 10710,
      hashrate: 9050,
      power: 3425,
      countInStock: 10,
      algorithm: 'scrypt',
      description:
        'Model Antminer L7 (9.05Gh) from Bitmain mining Scrypt algorithm with a maximum hashrate of 9.05Gh/s for a power consumption of 3425W.',
    },
    {
      name: 'S19XP',
      slug: 's19xp',
      category: 'Asics',
      image: '/images/S19XP.png',
      manufaturer: 'Bitmain',
      price: 6615,
      hashrate: 141,
      power: 3010,
      countInStock: 10,
      algorithm: 'SHA-256',
      description:
        'Model Antminer S19 XP (141Th) from Bitmain mining SHA-256 algorithm with a maximum hashrate of 141Th/s for a power consumption of 3010W.',
    },
    {
      name: 'Whatsminer M50',
      slug: 'whatsminer-m50',
      category: 'Asics',
      image: '/images/m50.png',
      manufaturer: 'MicroBT',
      price: 3385,
      hashrate: 118,
      power: 3306,
      countInStock: 10,
      algorithm: 'SHA-256',
      description:
        'Model Whatsminer M50 from MicroBT mining SHA-256 algorithm with a maximum hashrate of 118Th/s for a power consumption of 3306W.',
    },
    {
      name: 'KA3',
      slug: 'ka3',
      category: 'Asics',
      image: '/images/KA3.png',
      manufaturer: 'Bitmain',
      price: 12110,
      hashrate: 166,
      power: 3154,
      countInStock: 10,
      algorithm: 'Kadena',
      description:
        'Model Antminer KA3 (166Th) from Bitmain mining Kadena algorithm with a maximum hashrate of 166Th/s for a power consumption of 3154W.',
    },
    {
      name: 'Z15',
      slug: 'z15',
      category: 'Asics',
      image: '/images/Z15.png',
      manufaturer: 'Bitmain',
      price: 3710,
      hashrate: 420,
      power: 1510,
      countInStock: 10,
      algorithm: 'Equihash',
      description:
        'Model Antminer Z15 from Bitmain mining Equihash algorithm with a maximum hashrate of 420ksol/s for a power consumption of 1510W.',
    },
    {
      name: 'S19J Pro',
      slug: 's19j-pro',
      category: 'Asics',
      image: '/images/s19jpro.png',
      manufaturer: 'Bitmain',
      price: 2170,
      hashrate: 100,
      power: 3050,
      countInStock: 10,
      algorithm: 'SHA-256',
      description:
        'Model Antminer S19j Pro (100Th) from Bitmain mining SHA-256 algorithm with a maximum hashrate of 100Th/s for a power consumption of 3050W.',
    },
  ],
};

export default data;
